name: Deploy to server

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Change folder
        run: ls -la

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: |
          VITE_MAIN_API_URL=${{vars.MAIN_API_URL}} \
          npm run build
      - name: Remove to old static files from dev server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: sudo rm -rf ../../var/www/html/slovnyk/*

      - name: Deploy to dev server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: "build/*"
          target: "../../var/www/html/slovnyk/"
          strip_components: 1
